fix: 예외 테스트케이스 mock 로 변경, validation 의존성 추가
MockMvcBuilders.standaloneSetup() 로 mockMvc 객체 생성 시
Spring-boot-starter-validation 이 없으면 아래 오류가 발생하기 때문에 추가함.

NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found.